### ISSUE TITLE
製品区分(部門区分)を引数に所属社員一覧を返すテーブル値関数の作成

### ISSUE THREAD

**Issue by jms-funato** [jms-web/FMS#27]
**M016_SYONIN_TANTO**をベースに
**M004_SYAIN**、**M005_SYOZOKU_BUSYO**、**M002_BUSYO**を結合する

#### パラメータ
BUMON_KB AS char(1) ブランクあり

```sql
WHERE M002_BUSYO.BUMON_KB = [パラメータの製品区分]
```

#### 出力項目
 M016.[SYONIN_HOKOKUSYO_ID]
,M016.[SYONIN_JUN]
,M016.SYAIN_ID
,M004.SIMEI
,M002.BUMON_KB

※M004-M005が1対多なので、パラメータブランク時はSYAIN_IDが重複するしてしまうので、
BUMON_KBは該当レコードの先頭のものを使用する

**Comment by jms-fukuta** [comment]
TV02_SYONIN_SYOZOKU_SYAIN
のテーブル値関数として実装済
